### ISSUE TITLE
gpuocelot fail to build on  64-bit Ubuntu 12.04.1 LTS

### ISSUE THREAD

**Issue by slitvinov** [gtcasl/gpuocelot#101]
I am following the installation instruction on  64-bit Ubuntu 12.04.1 LTS
https://github.com/gtcasl/gpuocelot/wiki/Installation

`./build.py` fails with this error message

```
vagrant@vagrant-ubuntu-precise-64:~/gpuocelot/ocelot$     sudo ./build.py --install

scons -Q install=true
Build rules for Ocelot....
Failed to get subversion revision
Glew disabled: not found
Ocelot will be installed at /usr/local
config_h_build([".release_build/configure.h"], ["configure.h.in"])
g++ -o .release_build/ocelot/tools/OcelotConfig.o -c -O2 -Wall -Werror -std=c++0x -D_GNU_SOURCE -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS -DOCELOT_CXXFLAGS="\"-O2 -Wall -Werror -std=c++0x -D_GNU_SOURCE -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS\"" -DPACKAGE="\"ocelot\"" -DVERSION="\"2.1.0\"" -DOCELOT_PREFIX_PATH="\"/usr/local\"" -DOCELOT_LDFLAGS="\"-locelot\"" -L"\"/usr/local/lib\"" -DOCELOT_INCLUDE_PATH="\"/usr/local/include\"" -DOCELOT_LIB_PATH="\"/usr/local/lib\"" -DOCELOT_BIN_PATH="\"/usr/local/bin\"" -Ihydrazine -I. -I/usr/include -I/usr/include -I/usr/lib/llvm-2.9/include -I.release_build -I. ocelot/tools/OcelotConfig.cpp
ocelot/tools/OcelotConfig.cpp:14:48: fatal error: hydrazine/interface/ArgumentParser.h: No such file or directory
compilation terminated.
scons: *** [.release_build/ocelot/tools/OcelotConfig.o] Error 1
Build failed...
Build failed
```

**Comment by jwang323** [comment]
You will need to update the hydrazine submodule first. Under /path/to/gpuocelot:
  git submodule init; git submodule update;

The installation wiki has been updated.
